### ISSUE TITLE
Options not saved in Firefox nightly

### ISSUE THREAD

**Issue by jasontibbitts** [akahuku/wasavi#168]
Running the current (55.0a1 2017-05-11 64-bit) Linux version of Firefox nightly and wasavi/0.6.690, changes I make on the ``:options`` page are not saved.

Rather, it appears that while any changes take effect for the current browser session, those changes are not preserved after I restart the browser.  I can open the developer tools and watch the values in the extension's local storage change.  But somehow that doesn't appear to be saved to disk, or if it is it gets rewritten with default values when the browser next starts.  This goes for all the settings; I've tried to change the font, exrc, and fstab/preferred storage section and none of the changes appear to take.

I haven't been able to dig into this further (and I'm barely competent to do much more than look at the storage tab of the developer tools anyway) but I wanted to go ahead and open a ticket in case someone else has seen this.  Will now do some testing with other Firefox versions to make sure it's not something that nightly has broken.  I don't appear to have problems changing settings with other extensions, but then wasavi is a webext and most of my other extensions aren't so....

**Comment by jasontibbitts** [comment]
This continues into FF56a1.  It's also responsible for the wasavi welcome screen opening each time the browser starts, because wasavi thinks that it hasn't previously been run.

**Comment by akahuku** [comment]
Perhaps it should has been fixed with this [commit](https://github.com/akahuku/wasavi/commit/b396d19621450a056e56c890272c437076656c09#diff-cb352a64b5460e326790a022e0471f58).

**Comment by jasontibbitts** [comment]
Unfortunately I'm not seeing any change in behavior; preferences are still not being saved across browser restarts, and I get the wasavi startup page each time I start the browser.

According to :version I'm running 0.7.722, which I'm pretty sure should have that commit.  The Firefox extensions page says that I last updated on July 17 (which for me was yesterday).  I updated nightly this morning, though I see it wants to update again right now.

**Comment by akahuku** [comment]
I tried with following environment:

* xubuntu 16.04.02
* Firefox 56.0a1 with new profile
* wasavi 0.7.722

As a result, there seems to be no problem in saving wasavi's settings.
What will happen if you run Firefox Nightly with a new profile?

**Comment by jasontibbitts** [comment]
You are quite right; it works fine in Firefox nightly with a clean profile.  Now to try and figure out just what it is that's breaking things.

**Comment by dkarter** [comment]
@akahuku any chance you will support the new Firefox Quantum (v57)?

**Comment by jasontibbitts** [comment]
In what way does wasavi not support the current firefox versions?  I've been running wasavi with firefox nightly (now at FF59.0a1) for ages now and besides this issue which was fixed by cleaning out my ancient profile I've never had any problem running it.

**Comment by dkarter** [comment]
@jasontibbitts sorry for the confusion. I was searching for wasavi on the firefox add-ons directory here: https://addons.mozilla.org/en-US/firefox/ and could not find it. I was able to download it from the readme under "unstable version for firefox" and install it manually from a file. It would be nice to have it on the add-ons directory though.

Thanks for this amazing extension!
